<?php

declare(strict_types=1);

use TurboExcel\Concerns\FromArray;
use TurboExcel\Concerns\WithColumnFormatting;
use TurboExcel\Concerns\WithCsvOptions;
use TurboExcel\Concerns\WithHeadings;
use TurboExcel\Concerns\WithStyles;
use TurboExcel\Enums\Format;
use TurboExcel\Facades\TurboExcel;
use OpenSpout\Common\Entity\Style\Style;
use Illuminate\Support\Facades\File;

describe('Export Options', function (): void {
    it('applies csv options correctly', function (): void {
        $export = new class implements FromArray, WithCsvOptions {
            public function array(): array
            {
                // Adding the delimiter inside the string forces OpenSpout to use the enclosure 
                return [['first_name' => 'John', 'last_name' => 'Doe; Jr.']];
            }

            public function delimiter(): string
            {
                return ';';
            }

            public function enclosure(): string
            {
                return "'";
            }

            public function addBom(): bool
            {
                return false;
            }
        };

        $path = tmpPath('csv');
        TurboExcel::export($export, $path, Format::CSV);

        $content = File::get($path);
        
        // Check for specific enclosure and delimiter. 
        // OpenSpout only applies enclosures when the string contains the delimiter!
        expect($content)->toContain("John;'Doe; Jr.'");
    });

    it('can apply column styles and formats', function (): void {
        $export = new class implements FromArray, WithHeadings, WithStyles, WithColumnFormatting {
            public function array(): array
            {
                return [
                    ['amount' => 1000.50, 'date' => '2023-01-01'],
                ];
            }

            public function headings(): array
            {
                return ['Amount', 'Date'];
            }

            public function styles(): array
            {
                return [
                    'header' => (new Style())->setFontBold(),
                    'A'      => (new Style())->setFontItalic(),
                    // Override format from WithColumnFormatting via WithStyles
                    1        => (new Style())->setFormat('YYYY-MM-DD'),
                ];
            }

            public function columnFormats(): array
            {
                return [
                    'A' => '#,##0.00',
                    'B' => 'm/d/yy', // Should be overridden by style index 1 above
                ];
            }
        };

        $path = tmpPath('xlsx');
        TurboExcel::export($export, $path, Format::XLSX);

        expect(File::exists($path))->toBeTrue()
            ->and(File::size($path))->toBeGreaterThan(0);
        
        // Note: Verifying the actual XML generated by open spout requires extracting the zip.
        // We ensure it executes correctly without Exceptions and overrides apply.
    });

    it('emits debug logs when WithDebug is implemented', function (): void {
        \Illuminate\Support\Facades\Log::shouldReceive('info')
            ->twice()
            ->andReturnNull();

        $export = new class implements FromArray, \TurboExcel\Concerns\WithDebug {
            public function array(): array
            {
                return [['data' => 'yes']];
            }
        };

        TurboExcel::export($export, tmpPath('debug.xlsx'), Format::XLSX);
    });
});
